version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    depends_on:
      mysql:
        condition: service_healthy

  ui:
    build:
      context: ./UI
      dockerfile: dockerfile
    container_name: ui
    ports:
      - "3000:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Krishna4321!
      MYSQL_DATABASE: library_management
      MYSQL_USER: user
      MYSQL_PASSWORD: Krishna4321!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: 
    driver: local
    driver_opts:
      type: none
      device: ./mysql_data
      o: bind